In [3]:
import pandas as pd
from scipy import stats
import seaborn as sns

In [4]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
our_column = df['tip']
our_column = our_column.sample(n=30,replace=True)
meu = 3  # we assume that average tip is $3 and we want test it
t_statstics, p_value = stats.ttest_1samp(our_column,meu)
print('p-value:',p_value)

alpha = 0.5
if p_value < alpha:
    print('reject H0')
else:
    print('Do not reject H0')

p-value: 0.8929945664381916
Do not reject H0

In [11]:
# 2 sample T testing
male_tips=df[df['sex']=='Male']['tip']
female_tips=df[df['sex']=='Female']['tip']

male_tips=male_tips.sample(n=30,replace=False)
female_tips=female_tips.sample(n=30,replace=False)

t_statstics, p_value = stats.ttest_ind(male_tips,female_tips)
print('p-value:',p_value)
print("t_statstics :",t_statstics)
alpha = 0.5
if p_value < alpha:
    print('reject H0')
else:
    print('Do not reject H0')

p-value: 0.20445630599715034
t_statstics : 1.2833996430528447
reject H0

In [13]:
# paired test for t.1 and t.2
# H0:Treatment is not effective
# H1/Ha: It is effective
df = pd.read_csv('hypothermia.csv')
df = df[['t.1','t.2']].dropna()
sample_df = df.sample(n=30, replace=False)

t_statistic, p_value = stats.ttest_rel(sample_df['t.1'],sample_df['t.2'])
print('P-value:',p_value)

if p_value < alpha:
    print('reject H0')
else:
    print('Do not reject H0')

P-value: 6.564093315678126e-07
reject H0

In [14]:
df.head()

    t.1   t.2
0  34.0  35.1
1  29.0  33.0
2  31.0  36.8
3  32.0  34.0
4  32.2  36.6

In [15]:
#ANOVA
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [21]:

df.rename(columns={'size':'cust_count'},inplace=True)
df['tip_to_total']=df['tip']/df['total_bill']

s1=df.tip_to_total[df.cust_count==1]
s2=df.tip_to_total[df.cust_count==2]
s3=df.tip_to_total[df.cust_count==3]
s4=df.tip_to_total[df.cust_count==4]
s5=df.tip_to_total[df.cust_count==5]
s6=df.tip_to_total[df.cust_count==6]

#ANOVA
fstat,pval=stats.f_oneway(s1,s2,s3,s4,s5,s6)
alpha=0.05
print(pval)
if pval < alpha:
    print('Reject H0')
else:
    print("Do not reject H0")

0.16064144658923415
Do not reject H0

In [26]:
# chi-square test
from scipy.stats import chi2_contingency

df = sns.load_dataset('titanic')
df = df[['pclass','survived']].dropna()

contingency_table = pd.crosstab(df['pclass'],df['survived'])
print(contingency_table)

chi2_stat, p_value, dof, expected=chi2_contingency(contingency_table)
print('p-value:',p_value)

if p_value < alpha:
    print('Reject H0')
else:
    print("Do not reject H0")

survived    0    1
pclass
1          80  136
2          97   87
3         372  119
p-value: 4.549251711298793e-23
Reject H0